spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?characterEncoding=UTF-8&useSSL=false
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"