spring:
  datasource:
    url: jdbc:mysql://devops-db-release-mysql.devops.svc.cluster.local:3306/product_database?characterEncoding=UTF-8&useSSL=false
    username: root
    password: fjFXjCOd9l
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
